---
- name: Add Nginx repository
  apt_repository:
    repo: "{{ nginx_deb_repository }}"
  tags:
    - nginx-install

- name: Add Nginx repository key
  apt_key:
    keyserver: "{{ nginx_apt_key_server }}"
    id: "{{ nginx_apt_key_id }}"
  tags:
    - nginx-install
